#微服务建议一定要写服务端口号和微服务名称
server:
  #端口号
  port: 80
spring:
  application:
    #微服务名称
    name: cloud-consumer-order

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
